version: '3.9'
services:
    web-frontend-remix:
        build:
            context: './remix-frontend'
            dockerfile: Dockerfile
        restart: always
        ports:
            - "3000:3000"
        container_name: ashleshajewells-frontend-remix
        networks:
            - frontend-backend-network
        depends_on:
            - golang-backend
        deploy:
            resources:
                limits:
                    memory: 256M
                    cpus: "0.25"
    golang-backend:
        build:
            context: './golang-backend'
            dockerfile: Dockerfile
        restart: always
        ports:
            - "4000:4000"
        container_name: ashleshajewells-backend-golang
        networks:
            - frontend-backend-network
            - backend-db-network
        depends_on:
            - postgres-db
        volumes:
            - uploads:/app/uploads
            - invoices:/app/invoices
        deploy:
            resources:
                limits:
                    memory: 256M
                    cpus: "0.25"
    postgres-db:
        image: postgres:latest
        restart: always
        container_name: ashleshajewells-postgresdb
        environment:
            POSTGRES_USER: ashleshadbuser
            POSTGRES_PASSWORD: Ehsaas@2718
            POSTGRES_DB: ashleshajewells
        ports:
            - "5433:5432"
        volumes:
            - db:/var/lib/postgresql/data
        networks:
            - backend-db-network
        deploy:
            resources:
                limits:
                    memory: 512M
                    cpus: "0.5"
networks:
    frontend-backend-network:
    backend-db-network:
volumes:
    db:
        driver: local
    uploads:
        driver: local
    invoices:
        driver: local